### ISSUE TITLE
Expose `eth` endpoints critical to CLs

### ISSUE THREAD

**Issue by lightclient** [protolambda/mergemock#24]
Been meaning to do this, but keeps falling off my radar. Need to figure out which methods are needed but definitely:

* `eth_getBlockByNumber`

**Comment by metachris** [comment]
With `eth_getBlockByNumber` and `eth_getBlockByHash`, CL clients might have everything needed to get started testing the builder API with `mergemock relay`.

**Comment by tersec** [comment]
https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#underlying-protocol is the spec-complete set of such methods.
