### ISSUE TITLE
Track fee recipients upon validator registration

### ISSUE THREAD

**Issue by ralexstokes** [protolambda/mergemock#44]
I am doing some local integration testing using `mergemock` and it seems that the relay does not keep track of the validator's preferred fee recipient.

The code should be updated here https://github.com/protolambda/mergemock/blob/master/relay.go#L196 to fix this.

It seems from a quick pass this will need a `map` to track the pairs and also knowledge of the validator set to map public key to index (as each builder endpoint only gets one or the other but not both).

The implementation could skip the validator set mapping as a stopgap if it only assumes one "session" at a time (cf. the `latestPubkey` in the `relayBackend`)

edit: `mergemock` will pass the expected value if you supply it in a `forkChoiceUpdated` message

**Comment by metachris** [comment]
I'm curious what's the actual goal here, because the assumption is that real builders will set their own fee recipient and add a transaction to the validator's fee recipient to the end of the block 🤔

**Comment by ralexstokes** [comment]
> isn't this better mimicked by the current behaviour of a different fee recipient than the validator registered?

this part, yes :)

I was thinking it would be helpful during testing to know if the validator had a previously successful registration w/ the relay.

Right now, all you get back is a `200` HTTP code but things are early stage enough that I think it's a good spot check to see if the relay can serve back the one given in the registration.

I agree it may not be that important in the long run (and there will be other ways to verify, i.e. the validator can just simply check if they got paid (and possibly even w/ a proof!)) so we can consider this lower priority or even just close the issue.
